// source: study.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.variations.Study');
goog.provide('proto.variations.Study.ActivationType');
goog.provide('proto.variations.Study.Channel');
goog.provide('proto.variations.Study.Consistency');
goog.provide('proto.variations.Study.CpuArchitecture');
goog.provide('proto.variations.Study.Experiment');
goog.provide('proto.variations.Study.Experiment.FeatureAssociation');
goog.provide('proto.variations.Study.Experiment.OverrideUIString');
goog.provide('proto.variations.Study.Experiment.Param');
goog.provide('proto.variations.Study.Experiment.Type');
goog.provide('proto.variations.Study.Filter');
goog.provide('proto.variations.Study.FormFactor');
goog.provide('proto.variations.Study.GoogleWebVisibility');
goog.provide('proto.variations.Study.OptionalBool');
goog.provide('proto.variations.Study.Platform');
goog.provide('proto.variations.Study.PolicyRestriction');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.variations.LayerMemberReference');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.variations.Study = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.variations.Study.repeatedFields_, null);
};
goog.inherits(proto.variations.Study, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.variations.Study.displayName = 'proto.variations.Study';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.variations.Study.Experiment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.variations.Study.Experiment.repeatedFields_, null);
};
goog.inherits(proto.variations.Study.Experiment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.variations.Study.Experiment.displayName = 'proto.variations.Study.Experiment';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.variations.Study.Experiment.Param = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.variations.Study.Experiment.Param, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.variations.Study.Experiment.Param.displayName = 'proto.variations.Study.Experiment.Param';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.variations.Study.Experiment.FeatureAssociation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.variations.Study.Experiment.FeatureAssociation.repeatedFields_, null);
};
goog.inherits(proto.variations.Study.Experiment.FeatureAssociation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.variations.Study.Experiment.FeatureAssociation.displayName = 'proto.variations.Study.Experiment.FeatureAssociation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.variations.Study.Experiment.OverrideUIString = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.variations.Study.Experiment.OverrideUIString, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.variations.Study.Experiment.OverrideUIString.displayName = 'proto.variations.Study.Experiment.OverrideUIString';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.variations.Study.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.variations.Study.Filter.repeatedFields_, null);
};
goog.inherits(proto.variations.Study.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.variations.Study.Filter.displayName = 'proto.variations.Study.Filter';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.variations.Study.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.variations.Study.prototype.toObject = function(opt_includeInstance) {
  return proto.variations.Study.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.variations.Study} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    expiryDate: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    consistency: jspb.Message.getFieldWithDefault(msg, 7, 0),
    layer: (f = msg.getLayer()) && proto.variations.LayerMemberReference.toObject(includeInstance, f),
    defaultExperimentName: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    experimentList: jspb.Message.toObjectList(msg.getExperimentList(),
    proto.variations.Study.Experiment.toObject, includeInstance),
    filter: (f = msg.getFilter()) && proto.variations.Study.Filter.toObject(includeInstance, f),
    randomizationSeed: (f = jspb.Message.getField(msg, 11)) == null ? undefined : f,
    activationType: (f = jspb.Message.getField(msg, 12)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.variations.Study}
 */
proto.variations.Study.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.variations.Study;
  return proto.variations.Study.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.variations.Study} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.variations.Study}
 */
proto.variations.Study.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpiryDate(value);
      break;
    case 7:
      var value = /** @type {!proto.variations.Study.Consistency} */ (reader.readEnum());
      msg.setConsistency(value);
      break;
    case 16:
      var value = new proto.variations.LayerMemberReference;
      reader.readMessage(value,proto.variations.LayerMemberReference.deserializeBinaryFromReader);
      msg.setLayer(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDefaultExperimentName(value);
      break;
    case 9:
      var value = new proto.variations.Study.Experiment;
      reader.readMessage(value,proto.variations.Study.Experiment.deserializeBinaryFromReader);
      msg.addExperiment(value);
      break;
    case 10:
      var value = new proto.variations.Study.Filter;
      reader.readMessage(value,proto.variations.Study.Filter.deserializeBinaryFromReader);
      msg.setFilter(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRandomizationSeed(value);
      break;
    case 12:
      var value = /** @type {!proto.variations.Study.ActivationType} */ (reader.readEnum());
      msg.setActivationType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.variations.Study.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.variations.Study.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.variations.Study} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = /** @type {!proto.variations.Study.Consistency} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getLayer();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.variations.LayerMemberReference.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getExperimentList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.variations.Study.Experiment.serializeBinaryToWriter
    );
  }
  f = message.getFilter();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.variations.Study.Filter.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = /** @type {!proto.variations.Study.ActivationType} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeEnum(
      12,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.variations.Study.Consistency = {
  SESSION: 0,
  PERMANENT: 1
};

/**
 * @enum {number}
 */
proto.variations.Study.GoogleWebVisibility = {
  ANY: 0,
  FIRST_PARTY: 1
};

/**
 * @enum {number}
 */
proto.variations.Study.Channel = {
  UNKNOWN: -1,
  CANARY: 0,
  DEV: 1,
  BETA: 2,
  STABLE: 3
};

/**
 * @enum {number}
 */
proto.variations.Study.Platform = {
  PLATFORM_WINDOWS: 0,
  PLATFORM_MAC: 1,
  PLATFORM_LINUX: 2,
  PLATFORM_CHROMEOS: 3,
  PLATFORM_ANDROID: 4,
  PLATFORM_IOS: 5,
  PLATFORM_ANDROID_WEBVIEW: 6,
  PLATFORM_FUCHSIA: 7,
  PLATFORM_ANDROID_WEBLAYER: 8,
  PLATFORM_CHROMEOS_LACROS: 9
};

/**
 * @enum {number}
 */
proto.variations.Study.FormFactor = {
  DESKTOP: 0,
  PHONE: 1,
  TABLET: 2,
  KIOSK: 3,
  MEET_DEVICE: 4
};

/**
 * @enum {number}
 */
proto.variations.Study.CpuArchitecture = {
  X86_64: 0,
  ARM64: 1,
  X86_32: 2,
  ARM32: 3,
  TRANSLATED_X86_64: 4
};

/**
 * @enum {number}
 */
proto.variations.Study.OptionalBool = {
  OPTIONAL_BOOL_MISSING: 0,
  OPTIONAL_BOOL_TRUE: 1,
  OPTIONAL_BOOL_FALSE: 2
};

/**
 * @enum {number}
 */
proto.variations.Study.PolicyRestriction = {
  NONE: 0,
  CRITICAL: 1,
  CRITICAL_ONLY: 2
};

/**
 * @enum {number}
 */
proto.variations.Study.ActivationType = {
  ACTIVATE_ON_QUERY: 0,
  ACTIVATE_ON_STARTUP: 1
};


/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.variations.Study.Experiment.repeatedFields_ = [6,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.variations.Study.Experiment.prototype.toObject = function(opt_includeInstance) {
  return proto.variations.Study.Experiment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.variations.Study.Experiment} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Experiment.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    probabilityWeight: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    googleWebExperimentId: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    googleWebTriggerExperimentId: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    googleWebVisibility: (f = jspb.Message.getField(msg, 16)) == null ? undefined : f,
    chromeSyncExperimentId: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f,
    googleAppExperimentId: (f = jspb.Message.getField(msg, 15)) == null ? undefined : f,
    featureAssociation: (f = msg.getFeatureAssociation()) && proto.variations.Study.Experiment.FeatureAssociation.toObject(includeInstance, f),
    forcingFlag: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    paramList: jspb.Message.toObjectList(msg.getParamList(),
    proto.variations.Study.Experiment.Param.toObject, includeInstance),
    type: jspb.Message.getFieldWithDefault(msg, 7, 0),
    overrideUiStringList: jspb.Message.toObjectList(msg.getOverrideUiStringList(),
    proto.variations.Study.Experiment.OverrideUIString.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.variations.Study.Experiment}
 */
proto.variations.Study.Experiment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.variations.Study.Experiment;
  return proto.variations.Study.Experiment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.variations.Study.Experiment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.variations.Study.Experiment}
 */
proto.variations.Study.Experiment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setProbabilityWeight(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setGoogleWebExperimentId(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setGoogleWebTriggerExperimentId(value);
      break;
    case 16:
      var value = /** @type {!proto.variations.Study.GoogleWebVisibility} */ (reader.readEnum());
      msg.setGoogleWebVisibility(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setChromeSyncExperimentId(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setGoogleAppExperimentId(value);
      break;
    case 12:
      var value = new proto.variations.Study.Experiment.FeatureAssociation;
      reader.readMessage(value,proto.variations.Study.Experiment.FeatureAssociation.deserializeBinaryFromReader);
      msg.setFeatureAssociation(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setForcingFlag(value);
      break;
    case 6:
      var value = new proto.variations.Study.Experiment.Param;
      reader.readMessage(value,proto.variations.Study.Experiment.Param.deserializeBinaryFromReader);
      msg.addParam(value);
      break;
    case 7:
      var value = /** @type {!proto.variations.Study.Experiment.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 9:
      var value = new proto.variations.Study.Experiment.OverrideUIString;
      reader.readMessage(value,proto.variations.Study.Experiment.OverrideUIString.deserializeBinaryFromReader);
      msg.addOverrideUiString(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.variations.Study.Experiment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.variations.Study.Experiment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.variations.Study.Experiment} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Experiment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = /** @type {!proto.variations.Study.GoogleWebVisibility} */ (jspb.Message.getField(message, 16));
  if (f != null) {
    writer.writeEnum(
      16,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeUint64(
      15,
      f
    );
  }
  f = message.getFeatureAssociation();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.variations.Study.Experiment.FeatureAssociation.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getParamList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.variations.Study.Experiment.Param.serializeBinaryToWriter
    );
  }
  f = /** @type {!proto.variations.Study.Experiment.Type} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getOverrideUiStringList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.variations.Study.Experiment.OverrideUIString.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.variations.Study.Experiment.Type = {
  NORMAL: 0,
  IGNORE_CHANGE: 1,
  KILL_BEST_EFFORT: 2,
  KILL_CRITICAL: 3
};




if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.variations.Study.Experiment.Param.prototype.toObject = function(opt_includeInstance) {
  return proto.variations.Study.Experiment.Param.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.variations.Study.Experiment.Param} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Experiment.Param.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    value: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.variations.Study.Experiment.Param}
 */
proto.variations.Study.Experiment.Param.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.variations.Study.Experiment.Param;
  return proto.variations.Study.Experiment.Param.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.variations.Study.Experiment.Param} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.variations.Study.Experiment.Param}
 */
proto.variations.Study.Experiment.Param.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.variations.Study.Experiment.Param.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.variations.Study.Experiment.Param.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.variations.Study.Experiment.Param} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Experiment.Param.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.variations.Study.Experiment.Param.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Experiment.Param} returns this
 */
proto.variations.Study.Experiment.Param.prototype.setName = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment.Param} returns this
 */
proto.variations.Study.Experiment.Param.prototype.clearName = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.Param.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.variations.Study.Experiment.Param.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Experiment.Param} returns this
 */
proto.variations.Study.Experiment.Param.prototype.setValue = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment.Param} returns this
 */
proto.variations.Study.Experiment.Param.prototype.clearValue = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.Param.prototype.hasValue = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.variations.Study.Experiment.FeatureAssociation.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.toObject = function(opt_includeInstance) {
  return proto.variations.Study.Experiment.FeatureAssociation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.variations.Study.Experiment.FeatureAssociation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Experiment.FeatureAssociation.toObject = function(includeInstance, msg) {
  var f, obj = {
    enableFeatureList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    disableFeatureList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    forcingFeatureOn: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    forcingFeatureOff: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.variations.Study.Experiment.FeatureAssociation}
 */
proto.variations.Study.Experiment.FeatureAssociation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.variations.Study.Experiment.FeatureAssociation;
  return proto.variations.Study.Experiment.FeatureAssociation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.variations.Study.Experiment.FeatureAssociation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.variations.Study.Experiment.FeatureAssociation}
 */
proto.variations.Study.Experiment.FeatureAssociation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addEnableFeature(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addDisableFeature(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setForcingFeatureOn(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setForcingFeatureOff(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.variations.Study.Experiment.FeatureAssociation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.variations.Study.Experiment.FeatureAssociation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Experiment.FeatureAssociation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnableFeatureList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getDisableFeatureList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * repeated string enable_feature = 1;
 * @return {!Array<string>}
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.getEnableFeatureList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.setEnableFeatureList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.addEnableFeature = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.clearEnableFeatureList = function() {
  return this.setEnableFeatureList([]);
};


/**
 * repeated string disable_feature = 2;
 * @return {!Array<string>}
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.getDisableFeatureList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.setDisableFeatureList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.addDisableFeature = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.clearDisableFeatureList = function() {
  return this.setDisableFeatureList([]);
};


/**
 * optional string forcing_feature_on = 3;
 * @return {string}
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.getForcingFeatureOn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.setForcingFeatureOn = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.clearForcingFeatureOn = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.hasForcingFeatureOn = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string forcing_feature_off = 4;
 * @return {string}
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.getForcingFeatureOff = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.setForcingFeatureOff = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment.FeatureAssociation} returns this
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.clearForcingFeatureOff = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.FeatureAssociation.prototype.hasForcingFeatureOff = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.toObject = function(opt_includeInstance) {
  return proto.variations.Study.Experiment.OverrideUIString.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.variations.Study.Experiment.OverrideUIString} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Experiment.OverrideUIString.toObject = function(includeInstance, msg) {
  var f, obj = {
    nameHash: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    value: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.variations.Study.Experiment.OverrideUIString}
 */
proto.variations.Study.Experiment.OverrideUIString.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.variations.Study.Experiment.OverrideUIString;
  return proto.variations.Study.Experiment.OverrideUIString.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.variations.Study.Experiment.OverrideUIString} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.variations.Study.Experiment.OverrideUIString}
 */
proto.variations.Study.Experiment.OverrideUIString.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFixed32());
      msg.setNameHash(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.variations.Study.Experiment.OverrideUIString.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.variations.Study.Experiment.OverrideUIString} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Experiment.OverrideUIString.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeFixed32(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional fixed32 name_hash = 1;
 * @return {number}
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.getNameHash = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study.Experiment.OverrideUIString} returns this
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.setNameHash = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment.OverrideUIString} returns this
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.clearNameHash = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.hasNameHash = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Experiment.OverrideUIString} returns this
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.setValue = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment.OverrideUIString} returns this
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.clearValue = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.OverrideUIString.prototype.hasValue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required string name = 1;
 * @return {string}
 */
proto.variations.Study.Experiment.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.setName = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearName = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required uint32 probability_weight = 2;
 * @return {number}
 */
proto.variations.Study.Experiment.prototype.getProbabilityWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.setProbabilityWeight = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearProbabilityWeight = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasProbabilityWeight = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional uint64 google_web_experiment_id = 3;
 * @return {number}
 */
proto.variations.Study.Experiment.prototype.getGoogleWebExperimentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.setGoogleWebExperimentId = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearGoogleWebExperimentId = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasGoogleWebExperimentId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional uint64 google_web_trigger_experiment_id = 8;
 * @return {number}
 */
proto.variations.Study.Experiment.prototype.getGoogleWebTriggerExperimentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.setGoogleWebTriggerExperimentId = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearGoogleWebTriggerExperimentId = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasGoogleWebTriggerExperimentId = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional GoogleWebVisibility google_web_visibility = 16;
 * @return {!proto.variations.Study.GoogleWebVisibility}
 */
proto.variations.Study.Experiment.prototype.getGoogleWebVisibility = function() {
  return /** @type {!proto.variations.Study.GoogleWebVisibility} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {!proto.variations.Study.GoogleWebVisibility} value
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.setGoogleWebVisibility = function(value) {
  return jspb.Message.setField(this, 16, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearGoogleWebVisibility = function() {
  return jspb.Message.setField(this, 16, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasGoogleWebVisibility = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional uint64 chrome_sync_experiment_id = 10;
 * @return {number}
 */
proto.variations.Study.Experiment.prototype.getChromeSyncExperimentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.setChromeSyncExperimentId = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearChromeSyncExperimentId = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasChromeSyncExperimentId = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional uint64 google_app_experiment_id = 15;
 * @return {number}
 */
proto.variations.Study.Experiment.prototype.getGoogleAppExperimentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.setGoogleAppExperimentId = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearGoogleAppExperimentId = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasGoogleAppExperimentId = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional FeatureAssociation feature_association = 12;
 * @return {?proto.variations.Study.Experiment.FeatureAssociation}
 */
proto.variations.Study.Experiment.prototype.getFeatureAssociation = function() {
  return /** @type{?proto.variations.Study.Experiment.FeatureAssociation} */ (
    jspb.Message.getWrapperField(this, proto.variations.Study.Experiment.FeatureAssociation, 12));
};


/**
 * @param {?proto.variations.Study.Experiment.FeatureAssociation|undefined} value
 * @return {!proto.variations.Study.Experiment} returns this
*/
proto.variations.Study.Experiment.prototype.setFeatureAssociation = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearFeatureAssociation = function() {
  return this.setFeatureAssociation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasFeatureAssociation = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional string forcing_flag = 5;
 * @return {string}
 */
proto.variations.Study.Experiment.prototype.getForcingFlag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.setForcingFlag = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearForcingFlag = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasForcingFlag = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated Param param = 6;
 * @return {!Array<!proto.variations.Study.Experiment.Param>}
 */
proto.variations.Study.Experiment.prototype.getParamList = function() {
  return /** @type{!Array<!proto.variations.Study.Experiment.Param>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.variations.Study.Experiment.Param, 6));
};


/**
 * @param {!Array<!proto.variations.Study.Experiment.Param>} value
 * @return {!proto.variations.Study.Experiment} returns this
*/
proto.variations.Study.Experiment.prototype.setParamList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.variations.Study.Experiment.Param=} opt_value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Experiment.Param}
 */
proto.variations.Study.Experiment.prototype.addParam = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.variations.Study.Experiment.Param, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearParamList = function() {
  return this.setParamList([]);
};


/**
 * optional Type type = 7;
 * @return {!proto.variations.Study.Experiment.Type}
 */
proto.variations.Study.Experiment.prototype.getType = function() {
  return /** @type {!proto.variations.Study.Experiment.Type} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.variations.Study.Experiment.Type} value
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.setType = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearType = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Experiment.prototype.hasType = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated OverrideUIString override_ui_string = 9;
 * @return {!Array<!proto.variations.Study.Experiment.OverrideUIString>}
 */
proto.variations.Study.Experiment.prototype.getOverrideUiStringList = function() {
  return /** @type{!Array<!proto.variations.Study.Experiment.OverrideUIString>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.variations.Study.Experiment.OverrideUIString, 9));
};


/**
 * @param {!Array<!proto.variations.Study.Experiment.OverrideUIString>} value
 * @return {!proto.variations.Study.Experiment} returns this
*/
proto.variations.Study.Experiment.prototype.setOverrideUiStringList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.variations.Study.Experiment.OverrideUIString=} opt_value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Experiment.OverrideUIString}
 */
proto.variations.Study.Experiment.prototype.addOverrideUiString = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.variations.Study.Experiment.OverrideUIString, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Experiment} returns this
 */
proto.variations.Study.Experiment.prototype.clearOverrideUiStringList = function() {
  return this.setOverrideUiStringList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.variations.Study.Filter.repeatedFields_ = [4,5,6,12,7,14,8,9,10,11,20,21];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.variations.Study.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.variations.Study.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.variations.Study.Filter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
    startDate: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    endDate: (f = jspb.Message.getField(msg, 13)) == null ? undefined : f,
    minVersion: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    maxVersion: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    minOsVersion: (f = jspb.Message.getField(msg, 16)) == null ? undefined : f,
    maxOsVersion: (f = jspb.Message.getField(msg, 17)) == null ? undefined : f,
    channelList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    platformList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    localeList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    excludeLocaleList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    formFactorList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    excludeFormFactorList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    hardwareClassList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    excludeHardwareClassList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    countryList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    excludeCountryList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    isLowEndDevice: (f = jspb.Message.getBooleanField(msg, 15)) == null ? undefined : f,
    isEnterprise: (f = jspb.Message.getBooleanField(msg, 18)) == null ? undefined : f,
    policyRestriction: jspb.Message.getFieldWithDefault(msg, 19, 0),
    cpuArchitectureList: (f = jspb.Message.getRepeatedField(msg, 20)) == null ? undefined : f,
    excludeCpuArchitectureList: (f = jspb.Message.getRepeatedField(msg, 21)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.variations.Study.Filter}
 */
proto.variations.Study.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.variations.Study.Filter;
  return proto.variations.Study.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.variations.Study.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.variations.Study.Filter}
 */
proto.variations.Study.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartDate(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEndDate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMinVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaxVersion(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setMinOsVersion(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaxOsVersion(value);
      break;
    case 4:
      var values = /** @type {!Array<!proto.variations.Study.Channel>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addChannel(values[i]);
      }
      break;
    case 5:
      var values = /** @type {!Array<!proto.variations.Study.Platform>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPlatform(values[i]);
      }
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addLocale(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.addExcludeLocale(value);
      break;
    case 7:
      var values = /** @type {!Array<!proto.variations.Study.FormFactor>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addFormFactor(values[i]);
      }
      break;
    case 14:
      var values = /** @type {!Array<!proto.variations.Study.FormFactor>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addExcludeFormFactor(values[i]);
      }
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addHardwareClass(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addExcludeHardwareClass(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addCountry(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addExcludeCountry(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsLowEndDevice(value);
      break;
    case 18:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsEnterprise(value);
      break;
    case 19:
      var value = /** @type {!proto.variations.Study.PolicyRestriction} */ (reader.readEnum());
      msg.setPolicyRestriction(value);
      break;
    case 20:
      var values = /** @type {!Array<!proto.variations.Study.CpuArchitecture>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addCpuArchitecture(values[i]);
      }
      break;
    case 21:
      var values = /** @type {!Array<!proto.variations.Study.CpuArchitecture>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addExcludeCpuArchitecture(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.variations.Study.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.variations.Study.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.variations.Study.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.Study.Filter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 16));
  if (f != null) {
    writer.writeString(
      16,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getChannelList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      4,
      f
    );
  }
  f = message.getPlatformList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      5,
      f
    );
  }
  f = message.getLocaleList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getExcludeLocaleList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      12,
      f
    );
  }
  f = message.getFormFactorList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      7,
      f
    );
  }
  f = message.getExcludeFormFactorList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      14,
      f
    );
  }
  f = message.getHardwareClassList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
  f = message.getExcludeHardwareClassList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
  f = message.getCountryList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getExcludeCountryList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeBool(
      15,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 18));
  if (f != null) {
    writer.writeBool(
      18,
      f
    );
  }
  f = /** @type {!proto.variations.Study.PolicyRestriction} */ (jspb.Message.getField(message, 19));
  if (f != null) {
    writer.writeEnum(
      19,
      f
    );
  }
  f = message.getCpuArchitectureList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      20,
      f
    );
  }
  f = message.getExcludeCpuArchitectureList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      21,
      f
    );
  }
};


/**
 * optional int64 start_date = 1;
 * @return {number}
 */
proto.variations.Study.Filter.prototype.getStartDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setStartDate = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearStartDate = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.hasStartDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 end_date = 13;
 * @return {number}
 */
proto.variations.Study.Filter.prototype.getEndDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setEndDate = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearEndDate = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.hasEndDate = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional string min_version = 2;
 * @return {string}
 */
proto.variations.Study.Filter.prototype.getMinVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setMinVersion = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearMinVersion = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.hasMinVersion = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string max_version = 3;
 * @return {string}
 */
proto.variations.Study.Filter.prototype.getMaxVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setMaxVersion = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearMaxVersion = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.hasMaxVersion = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string min_os_version = 16;
 * @return {string}
 */
proto.variations.Study.Filter.prototype.getMinOsVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setMinOsVersion = function(value) {
  return jspb.Message.setField(this, 16, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearMinOsVersion = function() {
  return jspb.Message.setField(this, 16, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.hasMinOsVersion = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional string max_os_version = 17;
 * @return {string}
 */
proto.variations.Study.Filter.prototype.getMaxOsVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setMaxOsVersion = function(value) {
  return jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearMaxOsVersion = function() {
  return jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.hasMaxOsVersion = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * repeated Channel channel = 4;
 * @return {!Array<!proto.variations.Study.Channel>}
 */
proto.variations.Study.Filter.prototype.getChannelList = function() {
  return /** @type {!Array<!proto.variations.Study.Channel>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<!proto.variations.Study.Channel>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setChannelList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!proto.variations.Study.Channel} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addChannel = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearChannelList = function() {
  return this.setChannelList([]);
};


/**
 * repeated Platform platform = 5;
 * @return {!Array<!proto.variations.Study.Platform>}
 */
proto.variations.Study.Filter.prototype.getPlatformList = function() {
  return /** @type {!Array<!proto.variations.Study.Platform>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<!proto.variations.Study.Platform>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setPlatformList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!proto.variations.Study.Platform} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addPlatform = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearPlatformList = function() {
  return this.setPlatformList([]);
};


/**
 * repeated string locale = 6;
 * @return {!Array<string>}
 */
proto.variations.Study.Filter.prototype.getLocaleList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setLocaleList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addLocale = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearLocaleList = function() {
  return this.setLocaleList([]);
};


/**
 * repeated string exclude_locale = 12;
 * @return {!Array<string>}
 */
proto.variations.Study.Filter.prototype.getExcludeLocaleList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 12));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setExcludeLocaleList = function(value) {
  return jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addExcludeLocale = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearExcludeLocaleList = function() {
  return this.setExcludeLocaleList([]);
};


/**
 * repeated FormFactor form_factor = 7;
 * @return {!Array<!proto.variations.Study.FormFactor>}
 */
proto.variations.Study.Filter.prototype.getFormFactorList = function() {
  return /** @type {!Array<!proto.variations.Study.FormFactor>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<!proto.variations.Study.FormFactor>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setFormFactorList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!proto.variations.Study.FormFactor} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addFormFactor = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearFormFactorList = function() {
  return this.setFormFactorList([]);
};


/**
 * repeated FormFactor exclude_form_factor = 14;
 * @return {!Array<!proto.variations.Study.FormFactor>}
 */
proto.variations.Study.Filter.prototype.getExcludeFormFactorList = function() {
  return /** @type {!Array<!proto.variations.Study.FormFactor>} */ (jspb.Message.getRepeatedField(this, 14));
};


/**
 * @param {!Array<!proto.variations.Study.FormFactor>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setExcludeFormFactorList = function(value) {
  return jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {!proto.variations.Study.FormFactor} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addExcludeFormFactor = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearExcludeFormFactorList = function() {
  return this.setExcludeFormFactorList([]);
};


/**
 * repeated string hardware_class = 8;
 * @return {!Array<string>}
 */
proto.variations.Study.Filter.prototype.getHardwareClassList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setHardwareClassList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addHardwareClass = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearHardwareClassList = function() {
  return this.setHardwareClassList([]);
};


/**
 * repeated string exclude_hardware_class = 9;
 * @return {!Array<string>}
 */
proto.variations.Study.Filter.prototype.getExcludeHardwareClassList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setExcludeHardwareClassList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addExcludeHardwareClass = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearExcludeHardwareClassList = function() {
  return this.setExcludeHardwareClassList([]);
};


/**
 * repeated string country = 10;
 * @return {!Array<string>}
 */
proto.variations.Study.Filter.prototype.getCountryList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setCountryList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addCountry = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearCountryList = function() {
  return this.setCountryList([]);
};


/**
 * repeated string exclude_country = 11;
 * @return {!Array<string>}
 */
proto.variations.Study.Filter.prototype.getExcludeCountryList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setExcludeCountryList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addExcludeCountry = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearExcludeCountryList = function() {
  return this.setExcludeCountryList([]);
};


/**
 * optional bool is_low_end_device = 15;
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.getIsLowEndDevice = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setIsLowEndDevice = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearIsLowEndDevice = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.hasIsLowEndDevice = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional bool is_enterprise = 18;
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.getIsEnterprise = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 18, false));
};


/**
 * @param {boolean} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setIsEnterprise = function(value) {
  return jspb.Message.setField(this, 18, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearIsEnterprise = function() {
  return jspb.Message.setField(this, 18, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.hasIsEnterprise = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional PolicyRestriction policy_restriction = 19;
 * @return {!proto.variations.Study.PolicyRestriction}
 */
proto.variations.Study.Filter.prototype.getPolicyRestriction = function() {
  return /** @type {!proto.variations.Study.PolicyRestriction} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {!proto.variations.Study.PolicyRestriction} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setPolicyRestriction = function(value) {
  return jspb.Message.setField(this, 19, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearPolicyRestriction = function() {
  return jspb.Message.setField(this, 19, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.Filter.prototype.hasPolicyRestriction = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * repeated CpuArchitecture cpu_architecture = 20;
 * @return {!Array<!proto.variations.Study.CpuArchitecture>}
 */
proto.variations.Study.Filter.prototype.getCpuArchitectureList = function() {
  return /** @type {!Array<!proto.variations.Study.CpuArchitecture>} */ (jspb.Message.getRepeatedField(this, 20));
};


/**
 * @param {!Array<!proto.variations.Study.CpuArchitecture>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setCpuArchitectureList = function(value) {
  return jspb.Message.setField(this, 20, value || []);
};


/**
 * @param {!proto.variations.Study.CpuArchitecture} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addCpuArchitecture = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 20, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearCpuArchitectureList = function() {
  return this.setCpuArchitectureList([]);
};


/**
 * repeated CpuArchitecture exclude_cpu_architecture = 21;
 * @return {!Array<!proto.variations.Study.CpuArchitecture>}
 */
proto.variations.Study.Filter.prototype.getExcludeCpuArchitectureList = function() {
  return /** @type {!Array<!proto.variations.Study.CpuArchitecture>} */ (jspb.Message.getRepeatedField(this, 21));
};


/**
 * @param {!Array<!proto.variations.Study.CpuArchitecture>} value
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.setExcludeCpuArchitectureList = function(value) {
  return jspb.Message.setField(this, 21, value || []);
};


/**
 * @param {!proto.variations.Study.CpuArchitecture} value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.addExcludeCpuArchitecture = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 21, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study.Filter} returns this
 */
proto.variations.Study.Filter.prototype.clearExcludeCpuArchitectureList = function() {
  return this.setExcludeCpuArchitectureList([]);
};


/**
 * required string name = 1;
 * @return {string}
 */
proto.variations.Study.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.setName = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.clearName = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 expiry_date = 3;
 * @return {number}
 */
proto.variations.Study.prototype.getExpiryDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.setExpiryDate = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.clearExpiryDate = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.prototype.hasExpiryDate = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Consistency consistency = 7;
 * @return {!proto.variations.Study.Consistency}
 */
proto.variations.Study.prototype.getConsistency = function() {
  return /** @type {!proto.variations.Study.Consistency} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.variations.Study.Consistency} value
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.setConsistency = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.clearConsistency = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.prototype.hasConsistency = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional LayerMemberReference layer = 16;
 * @return {?proto.variations.LayerMemberReference}
 */
proto.variations.Study.prototype.getLayer = function() {
  return /** @type{?proto.variations.LayerMemberReference} */ (
    jspb.Message.getWrapperField(this, proto.variations.LayerMemberReference, 16));
};


/**
 * @param {?proto.variations.LayerMemberReference|undefined} value
 * @return {!proto.variations.Study} returns this
*/
proto.variations.Study.prototype.setLayer = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.clearLayer = function() {
  return this.setLayer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.prototype.hasLayer = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional string default_experiment_name = 8;
 * @return {string}
 */
proto.variations.Study.prototype.getDefaultExperimentName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.setDefaultExperimentName = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.clearDefaultExperimentName = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.prototype.hasDefaultExperimentName = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated Experiment experiment = 9;
 * @return {!Array<!proto.variations.Study.Experiment>}
 */
proto.variations.Study.prototype.getExperimentList = function() {
  return /** @type{!Array<!proto.variations.Study.Experiment>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.variations.Study.Experiment, 9));
};


/**
 * @param {!Array<!proto.variations.Study.Experiment>} value
 * @return {!proto.variations.Study} returns this
*/
proto.variations.Study.prototype.setExperimentList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.variations.Study.Experiment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.variations.Study.Experiment}
 */
proto.variations.Study.prototype.addExperiment = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.variations.Study.Experiment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.clearExperimentList = function() {
  return this.setExperimentList([]);
};


/**
 * optional Filter filter = 10;
 * @return {?proto.variations.Study.Filter}
 */
proto.variations.Study.prototype.getFilter = function() {
  return /** @type{?proto.variations.Study.Filter} */ (
    jspb.Message.getWrapperField(this, proto.variations.Study.Filter, 10));
};


/**
 * @param {?proto.variations.Study.Filter|undefined} value
 * @return {!proto.variations.Study} returns this
*/
proto.variations.Study.prototype.setFilter = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.clearFilter = function() {
  return this.setFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.prototype.hasFilter = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional uint32 randomization_seed = 11;
 * @return {number}
 */
proto.variations.Study.prototype.getRandomizationSeed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.setRandomizationSeed = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.clearRandomizationSeed = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.prototype.hasRandomizationSeed = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional ActivationType activation_type = 12;
 * @return {!proto.variations.Study.ActivationType}
 */
proto.variations.Study.prototype.getActivationType = function() {
  return /** @type {!proto.variations.Study.ActivationType} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {!proto.variations.Study.ActivationType} value
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.setActivationType = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.Study} returns this
 */
proto.variations.Study.prototype.clearActivationType = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.Study.prototype.hasActivationType = function() {
  return jspb.Message.getField(this, 12) != null;
};


