// source: variations_seed.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.variations.VariationsSeed');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.variations.Layer');
goog.require('proto.variations.Study');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.variations.VariationsSeed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.variations.VariationsSeed.repeatedFields_, null);
};
goog.inherits(proto.variations.VariationsSeed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.variations.VariationsSeed.displayName = 'proto.variations.VariationsSeed';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.variations.VariationsSeed.repeatedFields_ = [2,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.variations.VariationsSeed.prototype.toObject = function(opt_includeInstance) {
  return proto.variations.VariationsSeed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.variations.VariationsSeed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.VariationsSeed.toObject = function(includeInstance, msg) {
  var f, obj = {
    serialNumber: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    studyList: jspb.Message.toObjectList(msg.getStudyList(),
    proto.variations.Study.toObject, includeInstance),
    countryCode: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    version: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    layersList: jspb.Message.toObjectList(msg.getLayersList(),
    proto.variations.Layer.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.variations.VariationsSeed}
 */
proto.variations.VariationsSeed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.variations.VariationsSeed;
  return proto.variations.VariationsSeed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.variations.VariationsSeed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.variations.VariationsSeed}
 */
proto.variations.VariationsSeed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSerialNumber(value);
      break;
    case 2:
      var value = new proto.variations.Study;
      reader.readMessage(value,proto.variations.Study.deserializeBinaryFromReader);
      msg.addStudy(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountryCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 5:
      var value = new proto.variations.Layer;
      reader.readMessage(value,proto.variations.Layer.deserializeBinaryFromReader);
      msg.addLayers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.variations.VariationsSeed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.variations.VariationsSeed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.variations.VariationsSeed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.variations.VariationsSeed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStudyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.variations.Study.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLayersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.variations.Layer.serializeBinaryToWriter
    );
  }
};


/**
 * optional string serial_number = 1;
 * @return {string}
 */
proto.variations.VariationsSeed.prototype.getSerialNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.VariationsSeed} returns this
 */
proto.variations.VariationsSeed.prototype.setSerialNumber = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.VariationsSeed} returns this
 */
proto.variations.VariationsSeed.prototype.clearSerialNumber = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.VariationsSeed.prototype.hasSerialNumber = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Study study = 2;
 * @return {!Array<!proto.variations.Study>}
 */
proto.variations.VariationsSeed.prototype.getStudyList = function() {
  return /** @type{!Array<!proto.variations.Study>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.variations.Study, 2));
};


/**
 * @param {!Array<!proto.variations.Study>} value
 * @return {!proto.variations.VariationsSeed} returns this
*/
proto.variations.VariationsSeed.prototype.setStudyList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.variations.Study=} opt_value
 * @param {number=} opt_index
 * @return {!proto.variations.Study}
 */
proto.variations.VariationsSeed.prototype.addStudy = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.variations.Study, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.VariationsSeed} returns this
 */
proto.variations.VariationsSeed.prototype.clearStudyList = function() {
  return this.setStudyList([]);
};


/**
 * optional string country_code = 3;
 * @return {string}
 */
proto.variations.VariationsSeed.prototype.getCountryCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.VariationsSeed} returns this
 */
proto.variations.VariationsSeed.prototype.setCountryCode = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.VariationsSeed} returns this
 */
proto.variations.VariationsSeed.prototype.clearCountryCode = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.VariationsSeed.prototype.hasCountryCode = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string version = 4;
 * @return {string}
 */
proto.variations.VariationsSeed.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.variations.VariationsSeed} returns this
 */
proto.variations.VariationsSeed.prototype.setVersion = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.variations.VariationsSeed} returns this
 */
proto.variations.VariationsSeed.prototype.clearVersion = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.variations.VariationsSeed.prototype.hasVersion = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated Layer layers = 5;
 * @return {!Array<!proto.variations.Layer>}
 */
proto.variations.VariationsSeed.prototype.getLayersList = function() {
  return /** @type{!Array<!proto.variations.Layer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.variations.Layer, 5));
};


/**
 * @param {!Array<!proto.variations.Layer>} value
 * @return {!proto.variations.VariationsSeed} returns this
*/
proto.variations.VariationsSeed.prototype.setLayersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.variations.Layer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.variations.Layer}
 */
proto.variations.VariationsSeed.prototype.addLayers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.variations.Layer, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.variations.VariationsSeed} returns this
 */
proto.variations.VariationsSeed.prototype.clearLayersList = function() {
  return this.setLayersList([]);
};


